### ISSUE TITLE
Investigate possibility of using Microsoft.SqlServer.Types 160.900.6-rc0

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EntityFramework6PowerTools#103]

**Comment by ErikEJ** [comment]
@stevetalkscode Looks like it "just works"™  but I have just done a simple smoke test. I will publish a 6.6.0-rc1 package on NuGet that you can try

**Comment by ErikEJ** [comment]
Package published now: https://www.nuget.org/packages/ErikEJ.EntityFramework.SqlServer/6.6.0-rc1

**Comment by stevetalkscode** [comment]
Thanks @ErikEJ - just waiting for NuGet to index so that I can give it a try

**Comment by ErikEJ** [comment]
@stevetalkscode Looking forward to the result and yeah, NuGet seems to have some operational issue at the moment

**Comment by stevetalkscode** [comment]
Just downloaded and it fixes the issue I had with with context.SaveChanges. Many thanks. Just need to wait for the SQL Server team to release the RTM package

**Comment by ErikEJ** [comment]
>>  it fixes the issue I had with with context.SaveChanges

Amazing! Thanks for confirming
