### ISSUE TITLE
install on vs 2022 problem

### ISSUE THREAD

**Issue by mshojaei** [ErikEJ/EntityFramework6PowerTools#105]
hi
i cant install this usefull tool on my new version od visual studio 2022
i get this error at the first

VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products

**Comment by ErikEJ** [comment]
No, it is not available for VS 2022 - see #86 

What do you need it for in VS 2022?

**Comment by mshojaei** [comment]
I want it to generate ef views in code first project

**Comment by ErikEJ** [comment]
Doing that is described in the linked issue.
