### ISSUE TITLE
Debugging is slow, release mode is fast

### ISSUE THREAD

**Issue by mattdresch** [ErikEJ/EntityFramework6PowerTools#112]
For some reason, only when debugging (in both VS2019 and VS2022) Entity Framework connections and queries are incredibly slow. I don't have the same issue when running in release mode or when the code is deployed on the web server.

I am using Entity Framework 6.4.4 (Database First). The issue disappears when I revert back to using System.Data.SqlClient and EntityFramework 6.1.3, although it of course prevents me from using Azure Managed Identity.

**Comment by ErikEJ** [comment]
How does 6.4.4 act?

**Comment by mattdresch** [comment]
Thank you for the reply. 6.4.4 is what I am currently using due to the dependency in the latest version of ErikEJ.EntityFramework.SqlServer

**Comment by ErikEJ** [comment]
Yes but how does plain 6.4.4 behave?

**Comment by mattdresch** [comment]
It looks as though 6.1.3 is the latest version that is fine for us. Even upgrading to 6.2.0 we can observe the performance impact (only in debug mode). We were previously at version 6.1.3 but upgraded to 6.4.4 as recommended. 

I do see this issue, which never appeared to have been resolved: https://github.com/dotnet/ef6/issues/472

**Comment by ErikEJ** [comment]
Disable Visual Studio Diganostic tool
