### ISSUE TITLE
If have both vs 2012 and vs 2022, the installation wont work totally

### ISSUE THREAD

**Issue by Zero-Xiong** [ErikEJ/EntityFramework6PowerTools#126]
I have both vs 2012 and vs 2022 installed on my PC, now if I tried to install EF 6 Power Tools, it wont allow totally.

Is it possible allow user to apply the installation for vs 2012/vs2013/vs2015 if have?

===============================

5/24/2023 2:15:22 PM - Microsoft VSIX Installer
5/24/2023 2:15:22 PM - -------------------------------------------
5/24/2023 2:15:22 PM - vsixinstaller.exe version:
5/24/2023 2:15:22 PM - 17.6.2164+g40888c9894
5/24/2023 2:15:22 PM - -------------------------------------------
5/24/2023 2:15:22 PM - Command line parameters:
5/24/2023 2:15:22 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\xiongwh\Downloads\Entity Framework 6 Power Tools Community Edition v0.9.213.vsix
5/24/2023 2:15:22 PM - -------------------------------------------
5/24/2023 2:15:22 PM - Microsoft VSIX Installer
5/24/2023 2:15:22 PM - -------------------------------------------
5/24/2023 2:15:22 PM - Skipping product Microsoft.VisualStudio.Product.BuildTools (5ffb9491) since it does not support extensions
5/24/2023 2:15:22 PM - Initializing Install...
5/24/2023 2:15:22 PM - Searching for applicable products...
5/24/2023 2:15:22 PM - Found installed product - Visual Studio Professional 2022
5/24/2023 2:15:22 PM - Found installed product - Global Location
5/24/2023 2:15:22 PM - Extension Details...
5/24/2023 2:15:22 PM - 	Identifier         : F0A7D01D-4834-44C3-99B2-5907A0701906
5/24/2023 2:15:22 PM - 	Name               : Entity Framework 6 Power Tools Community Edition
5/24/2023 2:15:22 PM - 	Author             : ErikEJ
5/24/2023 2:15:22 PM - 	Version            : 0.9.213
5/24/2023 2:15:22 PM - 	Description        : Useful design-time utilities for EF 6, accessible through the Visual Studio Solution Explorer context menu.

**Comment by ErikEJ** [comment]
For VS 2012, you need to use this extension: https://marketplace.visualstudio.com/items?itemName=EntityFrameworkTeam.EntityFrameworkPowerToolsBeta4 and VS 2022 is not supported by this extension.

Why do you need it?

**Comment by ErikEJ** [comment]
Ping?
