### ISSUE TITLE
The new provider doesn't provide query logging information

### ISSUE THREAD

**Issue by jfrank14** [ErikEJ/EntityFramework6PowerTools#128]
With the `System.Data.SqlClient` provider, I set a `Log` callback like so:

```
If IsLocalhost() Then
  Database.Log = Sub(s) System.Diagnostics.Debug.Write(s.FixEntityFrameworkQueryVariables)
End If
```

and this would call my function with the huge EF query that it created, before trying to execute it. My callback, in turn, parsed these debug strings and the passed `@p__linq__1` variables, and emitted the query, for debugging purposes.

In the new provider, there's no debugging info, just "Opened connection" and "Closed connection", which is not so useful.

Is there a way to get this debug info with the new provider?

**Comment by ErikEJ** [comment]
I have a hard time understanding what is going on, can you please provide a simple repro?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
I am not able to reproduce
