### ISSUE TITLE
Microsoft.Data.SqlClient not used?

### ISSUE THREAD

**Issue by cveld** [ErikEJ/EntityFramework6PowerTools#129]
Any clue why Microsoft.Data.SqlClient is not used in the stack below?

```
[ArgumentException: Invalid value for key 'authentication'.]
   System.Data.Common.DbConnectionStringBuilderUtil.ConvertToAuthenticationType(String keyword, Object value) +393
   System.Data.SqlClient.SqlConnectionString.ConvertValueToAuthenticationType() +95
   System.Data.SqlClient.SqlConnectionString..ctor(String connectionString) +2223
   System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous) +25
   System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions) +166
   System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key) +57
   System.Data.SqlClient.SqlConnection.set_ConnectionString(String value) +148
   System.Data.Entity.Infrastructure.Interception.<>c.<SetConnectionString>b__8_0(DbConnection t, DbConnectionPropertyInterceptionContext`1 c) +17
   System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch(TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) +72
   System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.SetConnectionString(DbConnection connection, DbConnectionPropertyInterceptionContext`1 interceptionContext) +424
   System.Data.Entity.Internal.LazyInternalConnection.InitializeFromConnectionStringSetting(ConnectionStringSettings appConfigConnection) +269
   System.Data.Entity.Internal.LazyInternalConnection.TryInitializeFromAppConfig(String name, AppConfig config) +32
   System.Data.Entity.Internal.LazyInternalConnection.Initialize() +129
   System.Data.Entity.Internal.LazyInternalConnection.get_ProviderName() +13
   System.Data.Entity.Internal.LazyInternalContext.get_ProviderName() +11
   System.Data.Entity.Internal.DefaultModelCacheKeyFactory.Create(DbContext context) +92
   System.Data.Entity.Internal.LazyInternalContext.InitializeContext() +539
   System.Data.Entity.Internal.InternalContext.Initialize() +20
   System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType) +16
   System.Data.Entity.Internal.Linq.InternalSet`1.Initialize() +53
   System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext() +15
   System.Data.Entity.Infrastructure.DbQuery`1.System.Linq.IQueryable.get_Provider() +38
   System.Linq.Queryable.FirstOrDefault(IQueryable`1 source, Expression`1 predicate) +83
   nl.redacted.core.owin.client.<Register>d__0.MoveNext() +374
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +102
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +64
   nl.redacted.core.owin.client.<Configure>d__3`1.MoveNext() +581
```

Web.config has been amended as per https://github.com/ErikEJ/EntityFramework6PowerTools/blob/community/src/ErikEJ.EntityFramework.SqlServer/readme.md

When run locally the correct provider is picked. But when run in app service above exception is thrown.
Could be because I have separated out the connectionstrings in a separate file? 

Web.config:
`	<connectionStrings configSource="connectionStrings.config" />`

Connectionstrings.config:
```xml
<connectionStrings>
  <add name="AuthContext" connectionString="Server=tcp:redacted.database.windows.net,1433;Initial Catalog=redacted;Persist Security Info=False;Authentication=Active Directory Default;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" providerName="Microsoft.Data.SqlClient" />
</connectionStrings>
```

Edit; the place where the connectionstring is embedded in web.config doesn't seem to matter. It is completely overruled by the app service connectionstring settings.

dotnet framework 4.7.2

**Comment by ErikEJ** [comment]
Have you tried the latest daily build?

System.Data.SqlClient is used here because this code runs in the .NET Framework part of the extension.

**Comment by ErikEJ** [comment]
Sorry thought this was EF Core Power Tools. 

It is because you are still using System.Data.SqlClient somewhere. In you EDMX? - and have you set the code based configuration?

To help further you need to share a repro project.

**Comment by ErikEJ** [comment]
You can add an assert or test like this:

                Assert.True(ctx.Database.Connection as Microsoft.Data.SqlConnection != null);

**Comment by ErikEJ** [comment]
>> When run locally the correct provider is picked. 

How do you know that?

**Comment by ErikEJ** [comment]
Closing as per DM

**Comment by ErikEJ** [comment]
With Azure App Service configuration, the choice of AzureSql always returns ConnectionStringSettings.Provider as "System.Data.SqlClient"

Adding this to the DbConfiguration works around this
```
          SetProviderFactory("System.Data.SqlClient", Microsoft.Data.SqlClient.SqlClientFactory.Instance);
          SetProviderServices("System.Data.SqlClient", MicrosoftSqlProviderServices.Instance);
          SetExecutionStrategy("System.Data.SqlClient", () => new MicrosoftSqlAzureExecutionStrategy());
```

**Comment by ErikEJ** [comment]
I created this class in the same assembly as global asax:

public class AppServiceMicrosoftSqlDbConfiguration : DbConfiguration
    {
        const string SystemDataSqlClient = "System.Data.SqlClient";
        /// <summary>
        /// Default configuration, used for code based configuration of this provider.
        /// </summary>
        public AppServiceMicrosoftSqlDbConfiguration()
        {
            SetProviderFactory(SystemDataSqlClient, Microsoft.Data.SqlClient.SqlClientFactory.Instance);
            SetProviderServices(SystemDataSqlClient, MicrosoftSqlProviderServices.Instance);
            SetExecutionStrategy(SystemDataSqlClient, () => new MicrosoftSqlAzureExecutionStrategy());
        }
    }

Then in global.asax.cs I added the following line:

    protected void Application_Start(object sender, EventArgs e)
        {
            DbConfiguration.SetConfiguration(new AppServiceMicrosoftSqlDbConfiguration());         
        }
