### ISSUE TITLE
Invalid value for key 'authentication' 

### ISSUE THREAD

**Issue by VigneashSelvaraj** [ErikEJ/EntityFramework6PowerTools#130]
Hi - when I use Authentication key in my SQL connection string, I see above error. Can EF not process non sql auth ?

**Comment by ErikEJ** [comment]
It can, provided you use the correct underlying driver. When and where do you se this? In which VS version using which DDEX provider?

**Comment by ErikEJ** [comment]
Ah! You should use: https://github.com/ErikEJ/EntityFramework6PowerTools/blob/community/src/ErikEJ.EntityFramework.SqlServer/readme.md

**Comment by VigneashSelvaraj** [comment]
from the above readme file, does the DbContext class comes from System.Data.Entity namespace ?

**Comment by ErikEJ** [comment]
Yes

**Comment by VigneashSelvaraj** [comment]
Below is my app db context class 
using System;
using System.Data.Entity;
using System.Data.Entity.SqlServer;

namespace SampleApp.Databases
{
    [DbConfigurationType(typeof(MicrosoftSqlDbConfiguration))]
    public class SampleAppContext : DbContext, IDisposable, IContentValidationContext
    {
        public SampleAppContext(string connectionString) : base(connectionString)
        {

        }

Error I see:
System.ArgumentException
  HResult=0x80070057
  Message=Invalid value for key 'authentication'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by VigneashSelvaraj** [comment]
and the connection string is “Data Source= servername.database.windows.net; Encrypt=True; Initial Catalog= dbname; Authentication=Active Directory Service Principal; User Id=servicePrincipalID; Password=servicePrincipalPassword;”

**Comment by ErikEJ** [comment]
Please share a full repro if you want free support. Do you get this error locally or on your app service?

**Comment by VigneashSelvaraj** [comment]
This happens in my local.

**Comment by ErikEJ** [comment]
Maybe duplicate of https://github.com/ErikEJ/EntityFramework6PowerTools/issues/129 - otherwise share a full repro project.

**Comment by ErikEJ** [comment]
@VigneashSelvaraj Thanks, please share some repro steps. 

Why are you not using .NET ??

**Comment by ErikEJ** [comment]
Use this config! **That is why it is important to share all details!**

```xml
  <connectionStrings>
	  <add name="SqlConnectionString" connectionString="Data Source=servrename.database.windows.net;Encrypt=True;Initial Catalog=dbname;Authentication=Active Directory Service Principal;User Id=userid;Password=password;" providerName="Microsoft.Data.SqlClient" />
  </connectionStrings>
```

**Comment by VigneashSelvaraj** [comment]
thanks, it worked

**Comment by ErikEJ** [comment]
You are  welcome

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by VigneashSelvaraj** [comment]
Hi @ErikEJ 

In my web app, I do have a Business logic project holding Dbcontext. Can I just install ErikEJ.EntityFramework.SqlServer package in Business logic project alone ?  (or) do I have to install the same package in that web project calling BL project ?

**Comment by ErikEJ** [comment]
@VigneashSelvaraj What have you tried? Also, this issue is closed.
