### ISSUE TITLE
Could not find the resource error

### ISSUE THREAD

**Issue by holajan** [ErikEJ/EntityFramework6PowerTools#131]
Hello,
I have this error on Nuget version 6.6.5:

> An unhandled exception has occurred while executing the request.
> System.Data.DataException: Could not find the resource "System.Data.Entity.SqlServer.Properties.Resources.SqlServer.resources" among the resources "System.Data.Entity.SqlServer.Resources.Strings.resources", "System.Data.Resources.SqlClient.SqlProviderServices.StoreSchemaDefinition.ssdl", "System.Data.Resources.SqlClient.SqlProviderServices.StoreSchemaDefinitionVersion3.ssdl", "System.Data.Resources.SqlClient.SqlProviderServices.StoreSchemaMapping.msl", "System.Data.Resources.SqlClient.SqlProviderServices.StoreSchemaMappingVersion3.msl", "System.Data.Resources.SqlClient.SqlProviderServices.ProviderManifest.xml" embedded in the assembly "ErikEJ.EntityFramework.SqlServer", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
> ---> System.Resources.MissingManifestResourceException: Could not find the resource "System.Data.Entity.SqlServer.Properties.Resources.SqlServer.resources" among the resources "System.Data.Entity.SqlServer.Resources.Strings.resources", "System.Data.Resources.SqlClient.SqlProviderServices.StoreSchemaDefinition.ssdl", "System.Data.Resources.SqlClient.SqlProviderServices.StoreSchemaDefinitionVersion3.ssdl", "System.Data.Resources.SqlClient.SqlProviderServices.StoreSchemaMapping.msl", "System.Data.Resources.SqlClient.SqlProviderServices.StoreSchemaMappingVersion3.msl", "System.Data.Resources.SqlClient.SqlProviderServices.ProviderManifest.xml" embedded in the assembly "ErikEJ.EntityFramework.SqlServer", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.
>    at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
>    at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists)
>    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
>    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
>    at System.Data.Entity.SqlServer.Resources.EntityRes.GetString(String name) in /_/src/ErikEJ.EntityFramework.SqlServer/Properties/Resources.SqlServer.cs:line 572
>    at System.Data.Entity.SqlServer.Resources.Strings.get_TransientExceptionDetected() in /_/src/ErikEJ.EntityFramework.SqlServer/Properties/Resources.SqlServer.cs:line 366
>    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.ExecuteAsyncImplementation[TResult](Func`1 func) in /_/src/ErikEJ.EntityFramework.SqlServer/DefaultSqlExecutionStrategy.cs:line 96
>    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteStoreCommandInternalAsync(TransactionalBehavior transactionalBehavior, String commandText, CancellationToken cancellationToken, Object[] parameters)
> 

I thing error is because in constructor of **EntityRes** class is:
new ResourceManager("**System.Data.Entity.SqlServer.Properties.Resources.SqlServer**", ...
but in csproj file is

`<CustomToolNamespace>System.Data.Entity.SqlServer</CustomToolNamespace>`

without **Properties**.

**Comment by ErikEJ** [comment]
Can you provide a sample that generates the error?

**Comment by holajan** [comment]
I have not sample appliaction, the error is in our application at customer.
But to simulate this error it should be enough to have DefaultSqlExecutionStrategy and raise TimeoutException or SqlException with Number listed in SqlAzureRetriableExceptionDetector.

**Comment by ErikEJ** [comment]
Where do you see:

`<CustomToolNamespace>System.Data.Entity.SqlServer</CustomToolNamespace>`

**Comment by holajan** [comment]
In EntityFramework6PowerTools/src/ErikEJ.EntityFramework.SqlServer/ErikEJ.EntityFramework.SqlServer.csproj
https://github.com/ErikEJ/EntityFramework6PowerTools/blob/26fd793aa8b6888cbbdfdc6e5bb750c6d938dfaf/src/ErikEJ.EntityFramework.SqlServer/ErikEJ.EntityFramework.SqlServer.csproj

There is:
`<ItemGroup>
	<None Include="readme.md" Pack="true" PackagePath="\" />	  
    <None Update="Properties\Resources.SqlServer.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Resources.SqlServer.cs</LastGenOutput>
      <CustomToolNamespace>System.Data.Entity.SqlServer</CustomToolNamespace>
    </None>
  </ItemGroup>`

**Comment by ErikEJ** [comment]
Thanks, but it is same paths as in orginal project - it would be really helpful to get a small sample to reproduce the issue.

**Comment by holajan** [comment]
OK, I will try make sample

**Comment by ErikEJ** [comment]
Thanks for the repro. I have just pushed an updated package: https://www.nuget.org/packages/ErikEJ.EntityFramework.SqlServer/6.6.6-preview1 - would be grateful if you could verify it.

**Comment by holajan** [comment]
Tested. Now it works fine, thanks.

**Comment by ErikEJ** [comment]
@bricelam FYI:

Looks like the "official" provider is also affected by this, this test fails for .NET Core:

```csharp
       [Fact]
        public void CanLoadResources()
        {
            using (var ctx = new SchoolContext(new SqlConnection(ConnectionString)))
            {
                string sql = "RAISERROR(49918, 16, 1, 'Cannot process request. Not enough resources to process request.');";

                var ex = Assert.Throws<EntityException>(() => ctx.Database.ExecuteSqlCommand(sql));

                Assert.True(ex.InnerException is SqlException);
            }
        }

```

**Comment by ErikEJ** [comment]
@bricelam Unsure what the reason is, and my fix feels hacky

**Comment by ErikEJ** [comment]
@holajan Cool. I will release 6.6.6 soon

**Comment by ErikEJ** [comment]
@holajan 
If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)

**Comment by holajan** [comment]
I'm still looking at it. I believe there is still problem because this change was not made in the Resources.SqlServer.tt file so the resource class would be generated incorrectly.

**Comment by ErikEJ** [comment]
preview-2 is being published
