### ISSUE TITLE
Question about porting existing edmx model when using `ErikEJ.EntityFramework.SqlServer`& `Microsoft.Data.SqlClient`

### ISSUE THREAD

**Issue by DoctorVanGogh** [ErikEJ/EntityFramework6PowerTools#137]
I have a rather large-ish existing edmx based model and am trying to port this over from `System.Data.SqlClient` to `Microsoft.Data.SqlClient` in anticipation of a later migration to EF Core.

I've given your ErikEJ.EntityFramework.SqlServer package a spin, and cannot for the life of me get a 100% fully working version.

Changed/extended the `.config`s to 
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  ...
  <entityFramework>
      ...
      <providers >
          <provider invariantName="Microsoft.Data.SqlClient" type="System.Data.Entity.SqlServer.MicrosoftSqlProviderServices, ErikEJ.EntityFramework.SqlServer"/>
      </providers>
  </entityFramework>
  <connectionStrings >
    <add name="Foo"
      connectionString="metadata=res://*/foo.csdl|res://*/foo.ssdl|res://*/foo.msl;provider=Microsoft.Data.SqlClient;provider connection string=&quot;...&quot;"
      providerName="System.Data.EntityClient"/>
  </connectionStrings>
	<system.data>
		<DbProviderFactories >
			<add name="Microsoft SqlClient Data Provider" invariant="Microsoft.Data.SqlClient" description=".NET Framework Data Provider for SqlServer"
				type="Microsoft.Data.SqlClient.SqlClientFactory, Microsoft.Data.SqlClient"/>
		</DbProviderFactories>
	</system.data>
</configuration>
```
## Situation:
✅ Designer for the edmx continues to work
❓   _Most_ uses of `EntityContext` work, but not all[^dbcontext]

Digging around, the non working uses of `EntityContext` seems to happen when EF falls back to the underlying SSDL, which still has a reference to `System.Data.SqlClient` embedded 
```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="3.0" xmlns:edmx="http://schemas.microsoft.com/ado/2009/11/edmx">
  <!-- EF Runtime content -->
  <edmx:Runtime>
    <!-- SSDL content -->
    <edmx:StorageModels>
      <Schema Namespace="AdventureWorksModel.Store" Provider="System.Data.SqlClient" ProviderManifestToken="2012.Azure" ...>
      ...      
```
(See also [this issue](https://github.com/ErikEJ/EntityFramework6PowerTools/issues/127#issuecomment-1563401740)).

Manually editing the ssdl to use `Microsoft.Data.SqlClient` breaks the EDMX designer. It simply will no longer display the model, and looking at https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/plan#theme-clear-path-forward-from-ef6, specifically 

> In addition, we plan to make it clear on the [legacy EF6 GitHub repo](https://github.com/dotnet/ef6) that we are not planning any future work on EF6. The exception to this is that we plan to add support for using EF6 with [Microsoft.Data.SqlClient](https://github.com/dotnet/SqlClient). This will be limited to runtime support. **Use of the EF6 designer in Visual Studio will still require System.Data.SqlClient.**

[emphasis mine]

it seems that will not change[^eol]

Trying to create a _blank_ edmx model which uses `Microsoft.Data.SqlClient` just will not show the "new" provider:
![image](https://github.com/ErikEJ/EntityFramework6PowerTools/assets/324067/a67623eb-90ea-4d16-9dbc-971ae89965d2)
*`edmx` new connection dialog*

![image](https://github.com/ErikEJ/EntityFramework6PowerTools/assets/324067/f6d854e5-967b-46c9-8a80-51b13d9c3a3a)
*servcer browser new connection dialog*

## Possible Workaround idea:
The only option I can see is moving away from embedded metadata artefacts and having the `ssdl` (and `msl` & `csdl`) simply copied to the output directory, and *then* giving the `ssdl` a transformation pass[^transform] during build to switch from `System.Data`to `Microsoft.Data`.

---
Is there a simpler way to do this? I'm not really fond of the idea of inherently having different design & deplyment artefacts.

[^dbcontext]: In some call contexts the `DbContext` still tries to use `SqlCommand`|`Connection` etc. from `System.Data` instead of `Microsoft.Data`. Predictably this does not work.
[^eol]: It's regrettable, yet understandable that designer support for a technology - edmx files - that has been ~~abandoned~~ declared "EOL" is not getting any time allocated to it.
[^transform]: Either some manual text processing or maybe even a frankensteined application of `Microsoft.VisualStudio.SlowCheetah` transforms.

**Comment by ErikEJ** [comment]
Re 1: please share a repro, this sounds like a bug or bad configuration issue.

Re 2: which VS version? Newer versions should work with some patience,  as documented.
 
Re 3: see above, could be a non- issue

**Comment by DoctorVanGogh** [comment]
Thanks for the quick reply... but.... did you respond to my footnotes as "sub" issues? 😉 

Things I forgot to mention:
- Affected EntityContext comes from a customized T4, but it **does** have a `[DbConfigurationType(typeof(System.Data.Entity.SqlServer.MicrosoftSqlDbConfiguration))]` decoration on the entity class, so from my understanding it should *not* be a configuration issue.

  However, there is excessive "meddling" with connection strings going on, so I was assuming some things might hit an "unanticipated" fallback edge case inside DbContext base internals.
- Sadly this happening on VS 17.7 so it shouldn't be a toolset issue
- I'll _try_ to come up with a publishable repo case.

**Comment by ErikEJ** [comment]
Yes, I did respond to your footnotes.

Looking forward to a repro.

**Comment by DoctorVanGogh** [comment]
Here you go - cobbled together a "simple" example using a publicly hosted AdventureWorks on SqlServer.

https://github.com/DoctorVanGogh/MsSqlClientDemo/

Simple edmx model on AdventureWorks. App outputs the number of entities in the Address table.
```cs
        static void Main(string[] args) {
            try {
                using (var ctx = new AdventureWorksEntities()) {
                    Console.WriteLine($"{ctx.Address.Count()} adresses");
                }
            } catch (Exception ex) {
                Console.WriteLine(ex.ToString());
            }
        }
```
1. Branch [systemsqlclient](https://github.com/DoctorVanGogh/MsSqlClientDemo/tree/systemsqlclient) would be the "existing" model. 
**Result**: ✅ `450 adresses`  
2. Migration to MsSqlClient (ssdl not updated) in [mssqlclient/workingdesigner-brokenruntime](https://github.com/DoctorVanGogh/MsSqlClientDemo/tree/mssqlclient/workingdesigner-brokenruntime) branch:
**Result**: ⛔ 
  ```
System.InvalidCastException: Unable to cast object of type 'Microsoft.Data.SqlClient.SqlConnection' to type 'System.Data.SqlClient.SqlConnection'.
   at System.Data.SqlClient.SqlCommand.set_DbConnection(DbConnection value)
   at System.Data.Entity.Core.Common.Utils.CommandHelper.SetStoreProviderCommandState(EntityCommand entityCommand, EntityTransaction entityTransaction, DbCommand storeProviderCommand)
   ...
  ```
  3. Finally, editing the ssdl in branch [mssqlclient/brokendesigner-workingruntime](https://github.com/DoctorVanGogh/MsSqlClientDemo/tree/mssqlclient/brokendesigner-workingruntime)
    **Result**: ✅ `450 adresses`  
    Sadly, now *this* happens when you try opening the edmx designer:   
![image](https://github.com/ErikEJ/EntityFramework6PowerTools/assets/324067/0632e575-c68d-4981-88df-b5fd802380a5)
😒

**Comment by ErikEJ** [comment]
So it works, just not at design time?

**Comment by DoctorVanGogh** [comment]
Would that be "as expected"? 

Because no longer being able to tweak/update the model via the designer... is kinda a big thing.

Which leads me back to my "workaround" idea: Leave the ssdl "broken" but in a form where the designer works. Then modify the ssdl on build. _I just dont like it_. (And also have not yet cobbled together a working prototype, but it should be a "simple" arranging of mostly existing msbuild targets).

**Comment by ErikEJ** [comment]
>> Would that be "as expected"?

Yes, but I will make the docs clearer (not too clear atm)

I will have a look at your branch, maybe I can make it work.

**Comment by ErikEJ** [comment]
Ah! The project hosting the EDMX file cannot be a new SDK style project, it must be a classic .NET Framework C# project!

See my [blog post here](https://erikej.github.io/ef/dotnetcore/2020/06/15/ef6-use-edmx-dotnetcore.html)

**Comment by ErikEJ** [comment]
I have made som docs adjustments here: https://github.com/ErikEJ/EntityFramework6PowerTools/commit/d9adbd0f53b1496a7391637d6132eb4cd4dcd563

**Comment by DoctorVanGogh** [comment]
> Ah! The project hosting the EDMX file cannot be a new SDK style project, it must be a classic .NET Framework C# project!

Well, that's a clearly obvious and totally not arbitrary restriction :wink:

I think I'll go and beat my project with a stick instead. 
I should be able to slip in-between the `EntityDeploySplit` & `EntityDeployEmbeddedResources`/ `EntityDeployNonEmbeddedResources` msbuild targets from EF and do an in-place replacement for the provider inside the ssdl.

**Comment by DoctorVanGogh** [comment]
Okay.. found a solution:

Retain `System.Data.SqlClient` in the edmx Schema (so the deisigner works even in SDK style projects). Then edit the project file to reference a `.targets` file with the following:
```xml
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<!-- reference this .targets file to fix up edmx files which maintain 'Provider=Syste,Data.SqlClient' during build -->
	<!--  
		Why would you maintain "System.Data.SqlClient" in the raw edmx file? If you don't, the designer will not work in SDK style projects ;)		
	-->		
	<Target Name="EntitySSDLFixNonEmbedded"
			AfterTargets="EntityDeployNonEmbeddedResources">
		<ItemGroup>
			<!-- Target include paths taken from EF nuget package, build/EntityFramework.targets, EntityDeployNonEmbeddedResources target-->
			<EfSsdlFixFiles Include="@(EntityDeployCopyingItems->'$(OutputPath)%(EntityDeployRelativeDir)%(Filename).ssdl')" />
		</ItemGroup>		
	</Target>

	<Target Name="EntitySSDLFixEmbedded"
			AfterTargets="EntityDeployEmbeddedResources">
		<ItemGroup>
			<!-- Target include paths taken from EF nuget package, build/EntityFramework.targets, EntityDeployEmbeddedResources target -->
			<EfSsdlFixFiles Include="@(EntityDeployEmbeddingItems->'$(EntityDeployIntermediateResourcePath)%(EntityDeployRelativeDir)%(Filename).ssdl')" />
		</ItemGroup>				
	</Target>

	<Target Name="EntitySSDLFixCombined"
			BeforeTargets="EntityDeploySetLogicalNames"
			DependsOnTargets="EntitySSDLFixEmbedded;EntitySSDLFixNonEmbedded"
			Inputs="@(EfSsdlFixFiles)"
			Outputs="%(Identity).Dummy">
		<FixupSSDL Filename="@(EfSsdlFixFiles)" />
	</Target>	
	
	<UsingTask TaskName="FixupSSDL" TaskFactory="CodeTaskFactory" AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.v4.0.dll">
		<ParameterGroup>
			<Filename ParameterType="System.String" Required="true" />
		</ParameterGroup>
		<Task>
			<Reference Include="System.Core" />
			<Using Namespace="System" />
			<Using Namespace="System.IO" />
			<Using Namespace="System.Text.RegularExpressions" />
			<Code Type="Fragment" Language="cs">
				<![CDATA[
			String pattern = "System\\.Data\\.SqlClient";
			String replacement = "Microsoft.Data.SqlClient";
			
			String input = File.ReadAllText(Filename);			
			String output = Regex.Replace(input, pattern, replacement);			
			
			File.WriteAllText(Filename, output);
		  ]]>
			</Code>
		</Task>
	</UsingTask>

</Project>
```
Automatic replacements is not the prettiest, though I'm reasonably confident "System.Data.SqlClient" should *only* appear in one place in the ssdl. Could be done via xslt... I didnt feel like doing that.

Gives you:
- ✅ `450 adresses`
- Working designer:
![image](https://github.com/ErikEJ/EntityFramework6PowerTools/assets/324067/a1c23d87-85d7-4da3-9ec5-41139e9349aa)
- Works for both embedded & copied metadata artefacts

--- 
Feel free to include this workaround in the documentation and/or embed this in the nuget package (after whatever polish you feel this might need).

**Comment by ErikEJ** [comment]
Most people have their EDMX in a legacy project, not in an SDK style project. But now it is written down, thanks!
