### ISSUE TITLE
Error : The Provider Manifest is Incorrect

### ISSUE THREAD

**Issue by sivakumarkalluri** [ErikEJ/EntityFramework6PowerTools#138]
I was trying to create an ADO.Net Entity Data Model (Data base First Approach) for my application. I needed to connect to an Azure SQL Database using **Active Directory Service Principal** Authentication. Therefore, I installed ErikEJ.EntityFramework.SqlServer, as EF6 doesn't provide access to AD Service Principal authentication. However, while creating the Entity Data Model, I encountered the following error:

<img width="412" alt="MicrosoftTeams-image" src="https://github.com/ErikEJ/EntityFramework6PowerTools/assets/78248586/db0bba63-014c-4217-a10c-6f67fc8527e5">

### These are the steps I followed for creating the Entity Data Model (Database-First Approach):
<img width="371" alt="data provider" src="https://github.com/ErikEJ/EntityFramework6PowerTools/assets/78248586/0b828741-95ba-48b2-a1a2-cc3ff9574049">

- Selected the **Microsoft SqlClient Data Provider** as the data provider.
- In the Connection Properties, I selected SQL Server Authentication.
- **In the Advanced Properties, I provided Active Directory Service Principal as the authentication method.**
- Provided the necessary login credentials for the connection.
- When I performed the **Test Connection, it was successful.**
- However, when I proceeded to the next step, I encountered the following error:

<img width="412" alt="MicrosoftTeams-image" src="https://github.com/ErikEJ/EntityFramework6PowerTools/assets/78248586/bbd78e31-975b-4049-9a1c-0dec408a02db" style="margin-bottom: 20px;">

##
**Can I receive assistance in resolving this issue and determining what is causing it?**

**Comment by sivakumarkalluri** [comment]
> Did you read the readme? https://github.com/ErikEJ/EntityFramework6PowerTools/blob/community/src/ErikEJ.EntityFramework.SqlServer/readme.md#known-issues
> 
> Which VS version do you use? the designer should work for .NET Framework project with an updated VS install (as also mentioned in the readme)

I am using the VS 2022 version and .net 4.7.2v .
And EntityFramework.dll is also not available in the GAC

<img width="528" alt="GAC" src="https://github.com/ErikEJ/EntityFramework6PowerTools/assets/78248586/510b62cb-4b4a-4b1f-9e90-9658917b3f19">

**Comment by ErikEJ** [comment]
You should probably use System.Data.SqlClient with the designer then, and only Microsoft.Data.SqlClient at runtime - or share a repro.

**Comment by sivakumarkalluri** [comment]
> You should probably use System.Data.SqlClient with the designer then, and only Microsoft.Data.SqlClient at runtime - or share a repro.

I am utilizing the database-first approach in the Entity Data Model to create all the Model classes and DbContext. Consequently, there is no pre-existing code that I had written previously. When I choose the provider as "System.Data.SqlClient" and move on to the next step, the Entity Data Model wizard automatically closes, redirecting me back to the initial creation step.

**Comment by ErikEJ** [comment]
Something is broken on your machine.

**Comment by ErikEJ** [comment]
Closing as this is an unrelated Visual Studio issue.
