### ISSUE TITLE
A constructible type deriving from DbContext could not be found in the selected file

### ISSUE THREAD

**Issue by micheleissa** [ErikEJ/EntityFramework6PowerTools#14]
Hello,
 I have my Context deriven from IdentityDbContext which internally inherits from DbContext.  Entity Framework menu-item is available when I right-click the Context file. When I try to select View Entity Data Model DDL SQL option I get the error : 
A constructible type deriving from DbContext could not be found in the selected file
According to the readme, the tool works with any type derived from DbContext. 

Thanks

**Comment by ErikEJ** [comment]
Would be great if you could provide a repro porject

**Comment by micheleissa** [comment]
[TestEF.zip](https://github.com/ErikEJ/EntityFramework6PowerTools/files/1219538/TestEF.zip)
See attached
Thank you.

**Comment by ErikEJ** [comment]
Thanks for your repro project - EF Power Tools do not support EF Core!

**Comment by ErikEJ** [comment]
I see this in the description on MarketPlace:

Useful design-time utilities for **EF 6**, accessible through the Visual Studio Solution Explorer context menu.

When right-clicking on a file containing a derived DbContext class, the following context menu functions are available:
