### ISSUE TITLE
Interceptors are still using System.Data.SqlClient

### ISSUE THREAD

**Issue by swissarmykirpan** [ErikEJ/EntityFramework6PowerTools#141]
Hello,

I am trying to modify the connectionstring on the fly in a way that allows me to use the `IDbConnectionInterceptor` abstraction.

The problem I am running into is that it utilises the `System.Data.SqlClient` provider and so my connectionstrings which are for Sql Azure and use `managed identity`, do not work!

Can you suggest a workaround?

Kind regards,
Gurpreet

**Comment by ErikEJ** [comment]
Please provide more info -are you using my "new" provider? If so, please provide a runnable console app that demonstrates the issue, and I will have a look.
