### ISSUE TITLE
VPNGW/Private Endpoint from On Prem network connected via the VPNGW.

### ISSUE THREAD

**Issue by jwdaigle** [ErikEJ/EntityFramework6PowerTools#146]
We have a VPNGW set up, and a SQL Azure DB that has a private endpoint.  SSMS connects just fine using same connection string.  But when using the ErikEJ pkg, we get "Reason: An instance-specific error occurred while establishing a connection to SQL Server. Connection was denied since Deny Public Network Access is set to Yes (
https://docs.microsoft.com/azure/azure-sql/database/connectivity-settings#deny-public-network-access).
To connect to this server, use the Private Endpoint from inside your virtual network (
https://docs.microsoft.com/azure/sql-database/sql-database-private-endpoint-overview#how-to-set-up-private-link-for-azure-sql-database)."

It also works inside the Virtual LAN in Azure with SSMS and using your Pkg.

If I add a public IP address (defeating the purpose of having the VPNGW/Private Endpoint :-)) both SSMS and your pkg work.

Connection string is "Server=tcp:OurSQLSrvr.database.windows.net,1433;Initial Catalog=OurDB;Persist Security Info=False;User Id=Us;Password=GuessIt;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"

Any insight greatly appreciated!

**Comment by ErikEJ** [comment]
Not sure I understand how you can connect with SSMS from outside a private endpoint without a firwall exception??

**Comment by jwdaigle** [comment]
The combination of private endpoint and the VPN gateway enables access to the virtual network, including the subnet that azure sql is connected to via the virtual network interface the private nic provides.

It works for most azure resources that support private endpoints. VMs, key vaults, azure storage etc.

I'll send you azure learning docs if you wish.



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jwdaigle** [comment]
That is the full error message in the exception. I'll see if I can get the stack trace from the exception...

________________________________

**Comment by ErikEJ** [comment]
Are you running the app from the same machine as where you run SSMS?

**Comment by jwdaigle** [comment]
Yes

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ErikEJ** [comment]
Not stack trace received - could be name resolution or certificate related.
