### ISSUE TITLE
Can't Find Connectionstring match the DBContext

### ISSUE THREAD

**Issue by ChrisLethem** [ErikEJ/EntityFramework6PowerTools#15]
I Just installed the power tool so that I could get a visual of the data model.  But alas, I am unable to user the power tool as the extension is unable to find the connectstring in the web.config file. or the App.Config file.

**Comment by ErikEJ** [comment]
Is there a useable app.config file present in the project with the edmx model?

**Comment by ChrisLethem** [comment]
I implemented the code first with existing database. So no edmx file. 
I did then create an app.config file and added it to the project but I still received an error message that the connection string could not be found. 
I hope this info is helpful. 
Sincerely
Chris

**Comment by ErikEJ** [comment]
I think I would need a reproduction project.

**Comment by ChrisLethem** [comment]
Let me see if I can zip up the project for your perusal.
I will get something to you by tomorrow.
CHEERS
Chris Lethem

**Comment by ErikEJ** [comment]
Which power tools version do you have installed (you can see it in Help, About in VS) ?

**Comment by ErikEJ** [comment]
Closing as no repro project received -
