### ISSUE TITLE
Update to 5.2.1 and revert fix in CloneDbConnection

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EntityFramework6PowerTools#151]

**Comment by ErikEJ** [comment]
@rayao FYI https://github.com/dotnet/SqlClient/pull/2527

**Comment by ladeak** [comment]
I am not sure `CloneDbConnection` fixes the issue, after updating to 6.6.10 causes connection error on Linux.

Or it might, but there might be other issues which makes Microsoft.Data.SqlClient 5.2.0 unusable, there are bugfixes already being awaited for 5.2.1, for example: https://github.com/dotnet/SqlClient/issues/2378

**Comment by ErikEJ** [comment]
@ladeak Stay on 6.6.9 until 6.6.11 is released later this week, with MDS 5.2.1

**Comment by ErikEJ** [comment]
@ladeak @rayao I have just published 6.6.11
