### ISSUE TITLE
ADO.NET Model won't work

### ISSUE THREAD

**Issue by AxelLelong1** [ErikEJ/EntityFramework6PowerTools#155]
Created a brand new project, connected to a server, database
Added NuGet Packages entityFrameworkCore / SqlServer and Design

Right click, add componenent, ADO.NET Entity Data Model ...
![image](https://github.com/user-attachments/assets/1543541f-e6ef-473b-b876-ff43c99d4499)

.Net target runtime is 8.0

**Comment by ErikEJ** [comment]
This does not relate to this tool/repo, but as the error message states, .net 8 is not supported, you must use a .net framework project
