### ISSUE TITLE
Generate View is throwing Exception

### ISSUE THREAD

**Issue by tibinthk** [ErikEJ/EntityFramework6PowerTools#19]
I am getting the following exception, when I tried to create a precompiled view of a DB context.

The Entity framework Provider Type 'System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer' registred in the application config file for ADO.net provider with invariant Name 'System.Data.SqlClient' could not be loaded. Make Sure that the assembly-qualified name is used in the assembly is available to the running application.

![image](https://user-images.githubusercontent.com/20085151/31981822-223dab16-b973-11e7-91d6-50fe7630b5a4.png)

**Comment by ErikEJ** [comment]
Could you share your project? 
Also, which VS version and EF version?

**Comment by tibinthk** [comment]
EF 6.1.3
VS 2010 Professional

**Comment by ErikEJ** [comment]
OK, then you are not using this tool, it only works for VS 2015 and later
