### ISSUE TITLE
No Context Menu After Install

### ISSUE THREAD

**Issue by MajorMajor0** [ErikEJ/EntityFramework6PowerTools#24]
Windows 10
Visual Studio Community 2017 v 15.3.3

The application is currently built on the following
	- .NET 4.6.1
	- SQLite 1.0.106
	- Entity Framework 6.2.0
	- Database first

Apparent successful install of Entity Framework 6 Power Tools Community Edition 0.9.42
Extension shows up as installed under Extensions and updates
No Entity Framework context menu when right clicking on any file

**Comment by ErikEJ** [comment]
Is it a VB project?

**Comment by MajorMajor0** [comment]
No sir. C#, WPF.

**Comment by ErikEJ** [comment]
Can you provide a repro project.. ?

**Comment by MajorMajor0** [comment]
Will do this evening.

**Comment by MajorMajor0** [comment]
I should ask before you spend time debugging, is there a step I should have taken after running the vsix file to make the extension active in the project?

**Comment by MajorMajor0** [comment]
so posted screens of the other The connection string is hard-coded, so the project directory is "C:\Source\Repro" There is really nothing to this project. I've also posted screens of the other extensions that are apparently installed. I have no recollection of installing the overwhelming majority of these.


[Repro.zip](https://github.com/ErikEJ/EntityFramework6PowerTools/files/1516539/Repro.zip)


![ext1](https://user-images.githubusercontent.com/24254283/33413258-6bbbbe70-d545-11e7-9ef1-6135b56e85df.JPG)
![ext2](https://user-images.githubusercontent.com/24254283/33413260-6dcc0c24-d545-11e7-9f65-6449a50a9a68.JPG)

**Comment by MajorMajor0** [comment]
In addition to the Repro project above, the actual project is here.
https://github.com/MajorMajor0/Robin

**Comment by ErikEJ** [comment]
The PowerTools are mainly for projects without an EDMX file, in order to invoke them anyway, you must expand the EDMX file and right click on the ReproDataModel.Context.cs file to  get the "Entity Framework" menu

**Comment by MajorMajor0** [comment]
There is no context menu regardless of which file I click on. I don't really need any of the power tools other than generating views. I'm trying to precompile the views to speed up the first queries, which are painfully slow right now. All of the guidance that I've found on compiling views seems to not work with SQLite.

**Comment by ErikEJ** [comment]
I have no issue with getting the context menu to show on my system, for the Context.cs file or the EDMX file. So I am suspecting that your VS install is somehow broken, maybe you have duplicate installs of the extension, you can check you Extensions folder in %localappdata%

**Comment by MajorMajor0** [comment]
Thanks. Scrubbing VS deeply from the system and reinstalling solved the problem.

**Comment by JRichmond27** [comment]
> Is it a VB project?

@ErikEJ Is this extension only for C# projects?

**Comment by ErikEJ** [comment]
Yes

**Comment by JRichmond27** [comment]
Thanks. Couldn't find that info anywhere in the documentation.
