### ISSUE TITLE
安装之后，VS2017 菜单图标不见了

### ISSUE THREAD

**Issue by jason1004** [ErikEJ/EntityFramework6PowerTools#26]
![image](https://user-images.githubusercontent.com/13719529/33467059-d204a3c0-d68c-11e7-860e-422aab166119.png)

**Comment by ErikEJ** [comment]
How is this related to this extension?

**Comment by jason1004** [comment]
After installation, the menu is gone

**Comment by ErikEJ** [comment]
And if you uninstall?

**Comment by jason1004** [comment]
After uninstall the menu is still invisible, fix the vs to see. But once again, the menu is gone.

**Comment by ErikEJ** [comment]
Please describe step by step how this is related to EF 6 Power Tools

**Comment by ErikEJ** [comment]
Closing, as not details received - feel free to reopen when more details are available
