### ISSUE TITLE
lost future

### ISSUE THREAD

**Issue by adeewu** [ErikEJ/EntityFramework6PowerTools#32]
I can't find `Reverse Engineer Code First` `Customize Reverse Engineer Templates` on the project menu, then i check the source code, nothing about two future

**Comment by adeewu** [comment]
[see here](https://github.com/aspnet/EntityFramework6/tree/release-6.1.3-tools-update-2/src/PowerTools/Handlers), `AddCustomTemplatesHandler.cs` `ReverseEngineerCodeFirstHandler.cs` contain the future

**Comment by ErikEJ** [comment]
Those features are not available in the tool any longer, see the readme here: If you are looking for Reverse Engineeering tools, I recommend using the EF Reverse POCO Generator Template. You can also use the less advanced "Code First from Database" feature that is included with the standard Visual Studio tooling for EF 6.

**Comment by adeewu** [comment]
What a pity，it's cool future

**Comment by ErikEJ** [comment]
As I mentioned, there are two excellent replacements for this missing feature!
