### ISSUE TITLE
No context menu entries

### ISSUE THREAD

**Issue by XPD-Kasun** [ErikEJ/EntityFramework6PowerTools#33]
I have installed this extension into Visual Studio Community 2015 and restarted several times. But still I can't figure out any entries in solution explorer context menu for entity framework. Files with implementation of DbContext works properly by displaying a menu entry for Entity Framework. But for project menu there is no entry. This is a C# class library project which I've tested on.

**Comment by ErikEJ** [comment]
There is no project level menu! See the readme here
