### ISSUE TITLE
EF6 : A constructible type deriving from DbContext could not be found

### ISSUE THREAD

**Issue by rekna1** [ErikEJ/EntityFramework6PowerTools#34]
ParameterDbContext derives from DbContextBase derives from DbContext (EF6)
```
public class ParameterDbContext: DbContextBase, IParameterDbContext
...
public class DbContextBase : DbContext, IDbContext, IDisposable
```
Both derived and base class have parameterless constructor

But when trying to generate View Entity Data Model I get A constructible type deriving from DbContext could not be found

**Comment by ErikEJ** [comment]
Could you share a repro project?

**Comment by rekna1** [comment]
I'm not allowed to do that I'm afraid... 

Done some debugging 
```
in 
private dynamic DiscoverUserContextType(out Type systemContextType)
this
IEnumerable<CodeElement> enumerable = DbContextPackage.FindClassesInCodeModel(this._dte2.SelectedItems.Item(1).ProjectItem.FileCodeModel.CodeElements);
```
seems to return no elements...

Can't see what's in this.dte2.SelectedItems unfortunately

**Comment by ErikEJ** [comment]
Are you selecting the correct file?

**Comment by rekna1** [comment]
yes, the one that's containing ParameterContext : DbContextBase

**Comment by ErikEJ** [comment]
What if you select the class with DbContextBase ?

**Comment by rekna1** [comment]
It s in another assembly (comming from nuget package)

**Comment by ErikEJ** [comment]
Then maybe you are out of luck!?

**Comment by ErikEJ** [comment]
Closing as there is no obvious solution/workaround
