### ISSUE TITLE
any advice on trouble shooting "A constructible type deriving from DbContext could not be found"

### ISSUE THREAD

**Issue by jwaala** [ErikEJ/EntityFramework6PowerTools#35]
- not a .net core project
- ef/generate-view shows up when right clicking on any file (not just my DbContext file)
- have a no param constructor (see below)
- valid connection string entry for the name=DB in the app.config

```
    public partial class DB : DbContext
    {
        public DB() : base("name=DB")
        {
        }

        ...
    }
```

I get the "A constructible type deriving from DbContext could not be found" message in the IDE status bar at the bottom, but no other message/log/etc.

Would love to be able to figure this out.

**Comment by ErikEJ** [comment]
Can you share a repro project, and I will be happy to have a look

**Comment by jwaala** [comment]
it's a bit of a pain to trim this down, will give it a go and let you know

**Comment by jwaala** [comment]
very odd ... I trimmed thigns way down, now when I right click ef/gen/view ... I am getting an error dialog about sqlite, which is not being used, still hoping to get a repo to share

**Comment by ErikEJ** [comment]
Closing as no repro received, feel free to re-open if you can provide one
