### ISSUE TITLE
Cannot install EF Power Tools for 2017

### ISSUE THREAD

**Issue by LA2310** [ErikEJ/EntityFramework6PowerTools#38]
Hi,

I try to install this tool on my PC, but the VSIX Installer will not install this app.

I click on the button 'Install', after closing all necessary processes, nothing happens. The process bar is visible, but frozen and nothing will be installed.

I use VS2017 v.15.7.6

This is the state, where the installer is frozen:
![vsix_installer_problem](https://user-images.githubusercontent.com/42267101/43948949-8586a4f0-9c8c-11e8-8e45-5b0cf27d2217.png)

**Comment by ErikEJ** [comment]
Have you tried restarting your PC?

Have you tried repairing your VS installation?

**Comment by LA2310** [comment]
Yes, I tried it yesterday and this morning.
I installed the newest version of VS2017 yesterday.
And I repaired it minutes ago.

Nothing works...

**Comment by ErikEJ** [comment]
Can you install other extensions?

Have you tried another PC?

**Comment by LA2310** [comment]
Yes, we tried it on the computer of my colleague and there it works.
Only on my PC it will not install.

**Comment by LA2310** [comment]
Sorry, I accidentally closed it.

**Comment by ErikEJ** [comment]
Not sure I can help here...
