### ISSUE TITLE
No connection string named 'DBContext' could be found in the application config file.

### ISSUE THREAD

**Issue by trinhpham** [ErikEJ/EntityFramework6PowerTools#39]
Hello, I installed the latest release on VS Marketplace and face this problem when try with my project.
Clone the source code and debug it tell me that there are some problems:
1. The latest source code on branch community uses GetServiceAsync to get the DTE object, however, it doesn't wait for the object available before checking null => Fixed by adding await keyword
2. The ConfigurationManager somehow doesn't load my connectionstrings although the call to ConfigurationManager.OpenMappedExeConfiguration is succeeded. This cause the DBContext constructor cannot see my connection string and throws this error => Temporary fix by update ConfigurationManager.ConnectionStrings

I don't have enough knowledge to dig deeper into the issue, so I would like to post it here for any experts who could completely solve this issue.

My environment:
- Windows 10 Pro x64 17134.254
- VS 2017 15.8.1
- EntityFramework 6.2.0
- Target Framework: 4.6.1

You could find my fix at this [forked repo](https://github.com/trinhpham/EntityFramework6PowerTools.git)
A working build (tested on my computer only) could be downloaded [here](https://github.com/trinhpham/EntityFramework6PowerTools/releases/download/Fixed_connectionstrings/EFPowerTools.vsix)
As I don't think I found the root cause, so I don't create a PR for this. Just let me know if you want one.

**Comment by ErikEJ** [comment]
Thank, I have fixed the async bug in the latest commit.

Could you share a project that demonstrates your config issue?

**Comment by trinhpham** [comment]
@ErikEJ Sorry for this late response. There are a lot of things in my plate now.
My project is quite complex and cannot be opensource.
I'll try to make a sample with the issue and let you know as soon as I have time.

**Comment by ErikEJ** [comment]
Closing as the requested information was never supplied
