### ISSUE TITLE
Generate Entity Mapping Views through command line

### ISSUE THREAD

**Issue by whizkidwwe1217** [ErikEJ/EntityFramework6PowerTools#40]
It would be much better if I could also generate mapping views through command line. This will be very helpful in automating builds.

**Comment by ErikEJ** [comment]
Have you had a look at edmgen2 ?

**Comment by whizkidwwe1217** [comment]
@ErikEJ I haven't heard of it. I'll definitely check that out thanks!

**Comment by ErikEJ** [comment]
There is a GitHub repo with an updated version

**Comment by ErikEJ** [comment]
Yes

**Comment by whizkidwwe1217** [comment]
@ErikEJ EdmGen2 only works on .edmx files but not for code-first DbContexts

**Comment by ErikEJ** [comment]
Closing, as this seems out of scope for this project
