### ISSUE TITLE
Error 0152: No Entity Framework provider found for the ADO.NET provider with invariant name 'Oracle.ManagedDataAccess.Client'

### ISSUE THREAD

**Issue by anperim** [ErikEJ/EntityFramework6PowerTools#41]
Hi,
I´m trying to pre generate views on a db first (edmx) model and generate the follow error:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Data.Entity.Core.MetadataException: Schema specified is not valid. Errors: 
eEVNDataModel.edmx(7,6) : error 0152: No Entity Framework provider found for the ADO.NET provider with invariant name 'Oracle.ManagedDataAccess.Client'. Make sure the provider is registered in the 'entityFramework' section of the application config file. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.

I have the latest stable version of odp.net. The edmx has stored in a separated library and asp.net web application is running successfully. The app.config and web.config has same configurations.

**Comment by ErikEJ** [comment]
Which version of Visual Studio? There were issues with 15.7 and the EF Tools

**Comment by anperim** [comment]
15.8. Still have a bug with this version?

**Comment by ErikEJ** [comment]
Should be fixed, but I have no experience with the Oracle DDEX provider, sorry.

**Comment by anperim** [comment]
Thanks in advance.

Em seg, 8 de out de 2018 13:42, Erik Ejlskov Jensen <
notifications@github.com> escreveu:

**Comment by ErikEJ** [comment]
Appear to be an external VS related issue, closing

**Comment by anperim** [comment]
This is not a external issue. This is because the entity framework dll version inside visual Studio installation path can not load edmx. The project is running with entityframework nuget version and actually using the EFInteractiveViews as alternative.

**Comment by ErikEJ** [comment]
I meant that it was not an EF Powertools issue...

**Comment by anperim** [comment]
Ah ok. Thanks for all.

Em seg, 10 de dez de 2018 04:41, Erik Ejlskov Jensen <
notifications@github.com escreveu:
