### ISSUE TITLE
Issue with view data model with multiple projects

### ISSUE THREAD

**Issue by PhilPJL** [ErikEJ/EntityFramework6PowerTools#43]
[Test1.zip](https://github.com/ErikEJ/EntityFramework6PowerTools/files/2476577/Test1.zip)

If we have multiple projects where the derived DbContext have the same name, then attempting to view the data model fails if
1) view data model in project 1
2) attempt to view data model in project 2

We get 'this file has been modified outside the editor. Do you want to reload it?'
If we select yes then we get 'The file blah.edmx can be saved...'

The generated edmx probably needs to be <project name>.<context name>.edmx.

Just noticed this also happens if the contexts are in different solutions.

**Comment by ErikEJ** [comment]
>> The generated edmx probably needs to be ..edmx. 

Could you please explain what you mean by this?

**Comment by PhilPJL** [comment]
oops, the editor removed my angle brackets.
I meant instead of creating a file called "mycontext".edmx, we need a fully qualified name with the full project name "myproject"."mycontext".edmx.  Alternatively create the mycontext.edmx in a  sub-folder, like  ..\appdata\local\temp\"tempfolder" where tempfolder is unique.

**Comment by ErikEJ** [comment]
Got it - maybe you could submit a pull Request ?

**Comment by PhilPJL** [comment]
I'll give it a go.
