### ISSUE TITLE
Library not registered

### ISSUE THREAD

**Issue by uPloraX** [ErikEJ/EntityFramework6PowerTools#49]
Hey there, 
I'm trying to generate Views for my Code First Entity Framework but running into the issue, that some library is not registered.

![error_ef6](https://user-images.githubusercontent.com/20383017/49432633-71c76d80-f7b0-11e8-84c3-e6e93830a41a.PNG)

The connection string is build at runtime. Connection is made to an oracle database, so my App.config looks like that:

```
  <entityFramework>
    <defaultConnectionFactory type="Oracle.ManagedDataAccess.EntityFramework.OracleConnectionFactory, Oracle.ManagedDataAccess.EntityFramework"/>
    <providers>
      <provider invariantName="Oracle.ManagedDataAccess.Client"
        type="Oracle.ManagedDataAccess.EntityFramework.EFOracleProviderServices, Oracle.ManagedDataAccess.EntityFramework, Version=6.122.18.3, Culture=neutral, PublicKeyToken=89b483f429c47342"/>
    </providers>
  </entityFramework>
```

```
<system.data>
    <DbProviderFactories>
      <remove invariant="Oracle.ManagedDataAccess.Client"/>
      <add name="ODP.NET, Managed Driver" invariant="Oracle.ManagedDataAccess.Client" description="Oracle Data Provider for .NET, Managed Driver"
        type="Oracle.ManagedDataAccess.Client.OracleClientFactory, Oracle.ManagedDataAccess, Version=4.122.18.3, Culture=neutral, PublicKeyToken=89b483f429c47342"/>
    </DbProviderFactories>
</system.data>
```

I'm using Visual Studio 2017 Pro 15.9.3 with EF6 Power Tools 0.9.63.0.

**Comment by ErikEJ** [comment]
I think you need a tool like Process Explorer to find out what library is not registered...

**Comment by PhilPJL** [comment]
@ErikEJ I would be interested to see if the same error occurs with the latest build. @uPloraX are you able to build the latest code?

**Comment by ErikEJ** [comment]
The daily build is here: http://vsixgallery.com/extensions/F0A7D01D-4834-44C3-99B2-5907A0701906/extension.vsix

**Comment by PhilPJL** [comment]
Ah, ok  0.9,63 is the latest.

**Comment by ErikEJ** [comment]
Closing as the requested addtional information was never supplied
