### ISSUE TITLE
VS2019 Support for EF6 Power Tool

### ISSUE THREAD

**Issue by kkocabiyik** [ErikEJ/EntityFramework6PowerTools#51]
I saw you have upgraded EFCore Power Tools to VS 2019 on daily build. Is there any plan to do it on this project as well?

Thanks.

**Comment by ErikEJ** [comment]
Of course, and PRs accepted https://github.com/ErikEJ/SqlCeToolbox/commit/913f65f5812b6626383391e4a2a61b646a1985f3#diff-0eeeb9bc79ba8d16522b120e392ec20a

**Comment by ErikEJ** [comment]
Fixed in latest daily build, pls let me know if it works for you.

**Comment by kkocabiyik** [comment]
I tried and it's working properly.
Thanks a lot 👍
