### ISSUE TITLE
Cast issue from EF 5 to EF 6 ?

### ISSUE THREAD

**Issue by sphildreth** [ErikEJ/EntityFramework6PowerTools#56]
Greetings, I click on "View Entity Model (Read-Only)" in Visual Studio on my Context and I get this error:

![image](https://user-images.githubusercontent.com/193334/54857016-2a1b1200-4ccb-11e9-8e0f-d26c402a286c.png)

From my packages.config for the project:
```<package id="EntityFramework" version="6.2.0" targetFramework="net471" />```

Visual Studio Enterprise 15.9.9 on Windows 10.

**Comment by ErikEJ** [comment]
Maybe check if you have entityframework.dll in GAC, and then remove it

**Comment by sphildreth** [comment]
I removed and reinstalled Entity Framework Tools in Visual Studio setup and it starting working.
