### ISSUE TITLE
Customize Reverse Engineer Templates

### ISSUE THREAD

**Issue by bricelam** [ErikEJ/EntityFramework6PowerTools#57]
Per the discussion in https://github.com/aspnet/EntityFramework6/issues/883#issuecomment-499203044, it may be worth adding the `Customize Reverse Engineer Templates` command back.

This would add files under `CodeTemplates\EFModelFromDatabase` and replace the functionality of these packages (since `content` no longer works in NuGet with PackageReference):

- [EntityFramework.CodeTemplates.CSharp](https://www.nuget.org/packages/EntityFramework.CodeTemplates.CSharp)
- [EntityFramework.CodeTemplates.VisualBasic](https://www.nuget.org/packages/EntityFramework.CodeTemplates.VisualBasic)

**Comment by ErikEJ** [comment]
Interesting. So there is no way to include project content files with PackageReference ?

**Comment by bricelam** [comment]
No. You can include static content as part of the build, but it doesn’t help here since the content is supposed to be customized.

**Comment by bricelam** [comment]
This and the ability to modify config files are the biggest missing features in PackageReference

**Comment by ErikEJ** [comment]
Is the latest version of the tt files at this location? 
https://github.com/aspnet/EntityFramework6/tree/c8937b8089744c1b5e7ac4c2430bd29cd0c8d492

**Comment by ErikEJ** [comment]
Scratch that, I will just get the file from the 2 NuGet packages

**Comment by ErikEJ** [comment]
@bricelam Fixed in latest daily build
