### ISSUE TITLE
Where is EfTextTemplatingHost?

### ISSUE THREAD

**Issue by omatrot** [ErikEJ/EntityFramework6PowerTools#58]
I may be wrong but it seems that EfTextTemplatingHost is no longer included in the EF Power Tools.
Am I right?

I'm trying to solve [this problem](https://stackoverflow.com/questions/42772476/compiling-transformation-error-after-install-ef-power-tools-on-vs-community-2017).

**Comment by ErikEJ** [comment]
Well, reverse engineering is no longer supported, so I guess you are right, see the readme for alternatives

**Comment by ErikEJ** [comment]
Use alternative options
