### ISSUE TITLE
Error while selecting View Entity Data Model Options Visual Studio 2019

### ISSUE THREAD

**Issue by evertonvps** [ErikEJ/EntityFramework6PowerTools#59]
Hello! I'm trying to use power tools in a project with mysql. When selecting any View Entity Data Model option, visual studio displays the message **"The parameter is incorrect." (Exception from HRESUT: 0x80070057 (E_INVALIDARG))**

**Comment by ErikEJ** [comment]
Potentially a MySQL related issue. Can you Share a repro project?

**Comment by evertonvps** [comment]
I had to downgrade Mysql.Data to solve crash of EF's 
wizard and be able to reverse engineer Code First. 
Follow the link in the project.
https://we.tl/t-a8ci6GcE1K

**Comment by ErikEJ** [comment]
Then it sounds like a MySQL.Data issue, I think?

**Comment by evertonvps** [comment]
Yes! I tested it with SqlServer and it worked normally.

> Then it sounds like a MySQL.Data issue, I think?
