### ISSUE TITLE
Config file issue

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/EntityFramework6PowerTools#6]
See https://github.com/aspnet/EntityFramework6/issues/314

**Comment by ErikEJ** [comment]
Suggested fix did not work!

**Comment by fedora13** [comment]
Right click on the DataModel project and "Set as Startup Project" should help

**Comment by ErikEJ** [comment]
@fedora13 Was this a comment in regards to testing the fix? (Which is available in the daily build)

**Comment by fedora13** [comment]
@ErikEJ No, I guess. I download the tool today and had exactly same issue but I resolved it with the above step

**Comment by ErikEJ** [comment]
@fedora13 which error message did you get?

**Comment by fedora13** [comment]
@ErikEJ the error is "can't find the config file"..maybe because i set startup as my main app instead of the data model.  At first I thought it related to the issue #314

**Comment by ErikEJ** [comment]
I think it is not related...

**Comment by CZEMacLeod** [comment]
The new fix is working fine for me now.
I think we should add some mechanism for cleaning up the temp files after the commands have run though.

**Comment by ErikEJ** [comment]
Great news - I have logged: https://github.com/ErikEJ/EntityFramework6PowerTools/issues/10

**Comment by ErikEJ** [comment]
This is now live on Marketplace with clean up of temp files - thanks for a great contribution!
