### ISSUE TITLE
PowerTools with EF 6, Oracle.ManagedDataAccess and Oracle 11g

### ISSUE THREAD

**Issue by dmashcraft** [ErikEJ/EntityFramework6PowerTools#60]
ProviderIncompatibleException when trying to Generate Views.    Seems it's having trouble connecting to the database.    Any additional logging or info would be helpful.  Thanks.

**Comment by dmashcraft** [comment]
VS2017  forgot to mention that.

**Comment by ErikEJ** [comment]
I guess you could look in the output window, only other option would be to contact Oracle support

**Comment by ErikEJ** [comment]
Closing, external issue
