### ISSUE TITLE
Consider supporting new project system and .NET Core

### ISSUE THREAD

**Issue by divega** [ErikEJ/EntityFramework6PowerTools#62]
I know this is blocked by not having an EF6 designer that works on these projects yet, but wanted to add it anyway because today I ran into one project in which I wish I had had the option to run the power tools, and I wonder if this is something other power tools users would want.

cc @ErikEJ 

FWIW, currently you get this exception:

```
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.VisualStudio.Shell.Interop.IVsAggregatableProject'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{FFB2E715-7312-4B93-83D7-D37BCC561C90}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at Microsoft.DbContextPackage.Extensions.ProjectExtensions.GetProjectTypes(Project project)
   at Microsoft.DbContextPackage.Extensions.ProjectExtensions.IsWebProject(Project project)
   at Microsoft.DbContextPackage.DbContextPackage.GetUserConfig(Project project, String assemblyFullName)
   at Microsoft.DbContextPackage.DbContextPackage.DiscoverUserContextType(Type& systemContextType)
```

**Comment by rjmporter** [comment]
Likely related to this issue: Cannot use the solution file command extension to `View Entity Data Model [Read-Only | XML | DDL SQL ]` or `Generate Views` when EF types are defined in a shared project. Looks like a casting issue. `NullReferenceException` is thrown.

**Comment by ErikEJ** [comment]
No plans to do this
