### ISSUE TITLE
Error while generating view on visual studio 2019

### ISSUE THREAD

**Issue by abuthalhathpp** [ErikEJ/EntityFramework6PowerTools#64]
Could not load file or assembly 'System.ComponentModel.Annotations, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
System.ComponentModel.Annotations in my application is is 4.2.1.0
I updated the library to 4.7.0 still same error

**Comment by ErikEJ** [comment]
Which .NET Framework version do you have installed?

**Comment by abuthalhathpp** [comment]
.Net Framework 4.6.1

**Comment by ErikEJ** [comment]
Update to 4.7.2
