### ISSUE TITLE
Need options to generate POCO entities

### ISSUE THREAD

**Issue by karthiksubramaniam** [ErikEJ/EntityFramework6PowerTools#65]
Since [EntityFramework Reverse POCO Code First Generator](https://www.reversepoco.co.uk/) is moving towards pricing, can we have those POCO generating features here?

**Comment by ErikEJ** [comment]
Move to EF Core and use EF Core Power Tools (free) ??

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Actually, you can just use this: http://www.entityframeworktutorial.net/code-first/code-first-from-existing-database.aspx
