### ISSUE TITLE
No connection string could be found in application config file when generating views

### ISSUE THREAD

**Issue by DesertFoxAZ** [ErikEJ/EntityFramework6PowerTools#66]
![Connection string not found](https://user-images.githubusercontent.com/60105945/72739197-6f64d600-3b60-11ea-8e3d-77cff639813e.png)

For some projects I cannot generate a view and get a dialog stating that "No connection string named 'XXXXXXX' could be found in the application config file.". The connection string does in fact exist in the app.config or web.config files and matches the name of the DbContext file.

I can get this to work for some other projects and am unable to determine what specifically about the projects where it does not work is different when comparing it to the ones that do work.

**Comment by ErikEJ** [comment]
Unless you share a repro project it is going to be very hard for me to help you.

**Comment by DesertFoxAZ** [comment]
[DomainMonitoringApi.DataAccess..zip](https://github.com/ErikEJ/EntityFramework6PowerTools/files/4087526/DomainMonitoringApi.DataAccess.zip)
See attached. When I try creating the view at Models\DomainMonitoringApiContext.cs, I get the message shown above.

**Comment by JohnDoe2193** [comment]
I am getting the same problem. May I ask why it needs to read connection string? 

It seems all it should need is .CS file were database context is defined. In my case library project for which it tries to read App.config for doesn't even have App.config (it is a DLL library). So I just created a dummy App.config with empty connection string (correct string name but not server, database, user account) and it worked but I am not sure if the output was 100 correct.

**Comment by DesertFoxAZ** [comment]
I had my co-worker try it and he was able to get it to work. However, on my machine, it works sometimes and not others. I had created the views on one database before my original post but now I can't do it anymore. The other database that didn't work from the beginning still doesn't work.

**Comment by ErikEJ** [comment]
@desertfoxAZ Sound like it going to be very hard for me to repro - in addition, I cannot build your project

**Comment by ErikEJ** [comment]
Closing as unable to repro
