### ISSUE TITLE
Error generating Entity Data Models (Read-Only, XML, DDL SQL)

### ISSUE THREAD

**Issue by krptodr** [ErikEJ/EntityFramework6PowerTools#67]
I right click my context and and select either of the _View Entity Data Model_ options and get an error similar to:

> Could not load type \'\*.Business.Entities.Authentication.ApplicationUser\' from assembly \'\*.Business.Entities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'\.

_ApplicationUser_ inherits from _Microsoft.AspNet.Identity.EntityFramework.IdentityUser_

I've modified relationships on the other Identity tables, so that my ApplicationUser class could take advantage of the correct foreign key association(userId instead of ApplicationUser_Id).

**FluentAPI for ApplicationUser:**
```vbnet
Public Class Mappings
      Inherits Data.Entity.ModelConfiguration.EntityTypeConfiguration(Of ApplicationUser)

   Public Sub New()
      Me.ToTable("TableUser")
      Me.Property(Function(p) p.Id).HasColumnName("USERID")

      Me.Property(Function(p) p.Email).HasMaxLength(256).IsUnicode(False)
      Me.Property(Function(p) p.UserName).HasMaxLength(256).IsUnicode(False)
      Me.Property(Function(p) p.PasswordHash).HasMaxLength(256).IsUnicode(False)
      Me.Property(Function(p) p.SecurityStamp).HasMaxLength(256).IsUnicode(False)
      Me.Property(Function(p) p.PhoneNumber).HasMaxLength(256).IsUnicode(False)

      'Me.HasMany(Function(s) s.Logins).WithRequired().HasForeignKey(Function(f) f.UserId)
      'Me.HasMany(Function(s) s.Roles).WithRequired().HasForeignKey(Function(f) f.UserId)
      'Me.HasMany(Function(s) s.Claims).WithRequired().HasForeignKey(Function(f) f.UserId)
   End Sub
End Class
```

**Comment by ErikEJ** [comment]
And you use EF6

**Comment by krptodr** [comment]
@ErikEJ I apologize for the lack of detail. Yes EF 6.2

**Comment by ErikEJ** [comment]
Can you share a repro project?

**Comment by ErikEJ** [comment]
Closing this a  no repro provided, feel free to re-open if you can provide one.
