### ISSUE TITLE
EF6 Reverse Engineering

### ISSUE THREAD

**Issue by darklovesick** [ErikEJ/EntityFramework6PowerTools#69]
İ installed Entity Framework 6 Power Tools Community Edition. I am using VS2019.

I could not see Reverse Engineering Code First. Can You Help me please

How Can I show Reverse Engineering Code First

attach pic.
<img width="694" alt="noname" src="https://user-images.githubusercontent.com/37900479/78820076-e41d1300-79df-11ea-8274-576c4674af43.png">

**Comment by ErikEJ** [comment]
It is included in the standard EF Tools for visual studio. Read the readme in this repo!
