### ISSUE TITLE
Error generating models with VS2019 and EF6: A constructible type deriving....

### ISSUE THREAD

**Issue by pafuco** [ErikEJ/EntityFramework6PowerTools#70]
I use VS2019 and EF6. When I select any option from the menu to generate a model, I got the error "A constructible type deriving from DbContext could not be found in the selected file".

This an example of a DbContext Class

public class StoreContext : DbContext
    {        
        public StoreContext(DbContextOptions<StoreContext> options)
            : base(options) 
        {
            
        }

        public DbSet<Computer> Computers { get; set; }
        public DbSet<Allocation> Allocations { get; set; }
        public DbSet<Component> Components { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Component>().ToTable("Component");
            modelBuilder.Entity<Allocation>().ToTable("Allocation");
            modelBuilder.Entity<Computer>().ToTable("Computer");
        }
    }

**Comment by ErikEJ** [comment]
That does not look like a EF6 DbContext, that looks like a EF Core DbContext !?

**Comment by pafuco** [comment]
Thanks Erik for your clarification, it is right. Then I guess that in this case the correct would have been to use EF Core Power Tools.

**Comment by ErikEJ** [comment]
Yes!
