### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by nlnpraveen** [ErikEJ/EntityFramework6PowerTools#73]
Hi,

When I try to view the read-only entity data model it always throws the error shown on the title. The model was generated using the EF Reverse POCO Generator Template. When I run the code to fetch the data using the context it works fine. Do we know any other known causes as to why this issue might occur? Any help is appreciated.

Thanks, P

**Comment by ErikEJ** [comment]
I think you should address this in the EF Reverse POCO repository.
