### ISSUE TITLE
Is there a powershell commandlet to call Generate Views?

### ISSUE THREAD

**Issue by gregveres** [ErikEJ/EntityFramework6PowerTools#75]
I started using generate views, but I find the workflow really cumbersome to have to go find my DBContext file and right click to get to Generate Views. 

Is there a way to call this from powershell since I already have powershell open since I just did an add-migration and I  am about to do an update-database.

Thanks

**Comment by ErikEJ** [comment]
No, there is not any way to generate views from Powershell
