### ISSUE TITLE
Problem creatings Views

### ISSUE THREAD

**Issue by jonius40** [ErikEJ/EntityFramework6PowerTools#76]
Hi,
I am trying to create compiled views, using Generate Views . I am getting object of type  System.Linq.ExpressionExpression.Func2 {name of the object}, System Nullable1 [ System.Decimal] cannot be converted to type. I am using Visual Studio community 2019 with EF 6.1.2

King regards
John Papoutsidis

**Comment by ErikEJ** [comment]
Can you (privately) share a repro project?

**Comment by jonius40** [comment]
Hi Erik,
Thank you very much for answering. I can't send it because it is not mine.
It takes 4 minutes for first query to start! 1200 tables.

Kind regards
John Papoutsidis

**Comment by jonius40** [comment]
Hi Erik,
I will try to issolate the model class with the problem and  try to
reproduse it. After that i will send you the project.

**Comment by jonius40** [comment]
Well the problem is related with a custom Attribute used with a decimal value. When i start a new project creating the same attribute for testing power tools works fine. Both project have framework 4.5

**Comment by ErikEJ** [comment]
Unless I get a repro I cannot assist.
