### ISSUE TITLE
Cannot generate Views on EF 6.4.4

### ISSUE THREAD

**Issue by garyhalb** [ErikEJ/EntityFramework6PowerTools#77]
After upgrading to EF 6.4.4 I can no longer generate Views. The error is 'Exception has been thrown by the target of an invocation'.

Tried re-installing, tried on an older version using a lower version of EF and it works fine.

**Comment by ErikEJ** [comment]
Duplicate of #76 ?

**Comment by ErikEJ** [comment]
Which "older versions" worked? 
can you share a repro?

**Comment by garyhalb** [comment]
This is in VS2015 Community. Tried to create a bare-bones repo, and now getting a Sequence contains no elements error instead. See attached:
[ClassLibrary1.zip](https://github.com/ErikEJ/EntityFramework6PowerTools/files/5865023/ClassLibrary1.zip)

**Comment by garyhalb** [comment]
Potentially something to do with Enums in a seperate class.

**Comment by garyhalb** [comment]
Tried downgrading to 6.2.0 and had the same issue. Finally downgraded back to 6.1.3 and view generation works again.

**Comment by ErikEJ** [comment]
I am unable to repro with ClassLibrary1 as Startup project, and using VS 2019 latest. (EF 6.4.4) - in other words, view generation works fine for me.

**Comment by garyhalb** [comment]
I can confirm the same result today. View generation working on the sample, but still not in my main solution. Will try create another repro.

**Comment by garyhalb** [comment]
What's the easiest way to get you a private repo link?

**Comment by ErikEJ** [comment]
You can email me at ejlskov at hotmail dot com

**Comment by garyhalb** [comment]
Thanks, I've done so.

**Comment by ErikEJ** [comment]
Invalid code in the dervied DbConfiguration class caused this error, latest daily build contains improved error logging.

**Comment by garyhalb** [comment]
Excellent, thank you so much.
