### ISSUE TITLE
The tool not supports latest npgsql versions

### ISSUE THREAD

**Issue by ekondur** [ErikEJ/EntityFramework6PowerTools#78]
Hi @ErikEJ,
thanks for amazing job. we use the tool for generate views and it can not work with npgsql new versions. ( it supports to 3.1.0 i think.) do you know it and any plan about it?
thanks.

**Comment by ErikEJ** [comment]
How does the lack of support manifest itself?

**Comment by ekondur** [comment]
It throws an error -> A constructible type deriving from DbContext could not be found in selected file
If we use npgsql version 4+

**Comment by ErikEJ** [comment]
@roji ??

**Comment by ekondur** [comment]
Hi @ErikEJ ,
I think another dependencies caused it. I fixed. Thank you.

**Comment by ErikEJ** [comment]
Can you share what / how it was fixed?

**Comment by ekondur** [comment]
the project included context, needs another dll we have (for IOC). I referenced also this.

**Comment by ErikEJ** [comment]
Thanks. Did the stack trace in the Build window help you trouble shoot this?

**Comment by ekondur** [comment]
Yes I did, when I upgrade it, throw this dll ecxeption, "it depends bla-bla dll"
*bla-bla is our IOC package :)
