### ISSUE TITLE
Ignore HasSequence  in generation

### ISSUE THREAD

**Issue by alvpaz** [ErikEJ/EntityFramework6PowerTools#80]
I would like to ignore modelBuilder.HasSequence

![image](https://user-images.githubusercontent.com/7883678/124022560-57cf8500-d9c3-11eb-8c52-253eb4afa2b4.png)

**Comment by ErikEJ** [comment]
Why is that important in generated code?

**Comment by alvpaz** [comment]
That's not the sequence, it changes as new records are added, so I don't need to have this information.

**Comment by ErikEJ** [comment]
Is this EF6?

Also, can you provide more details??

**Comment by ErikEJ** [comment]
Closing as the requested details were never provided
