### ISSUE TITLE
Defaults not set in Table

### ISSUE THREAD

**Issue by LeopoldLerch** [ErikEJ/EntityFramework6PowerTools#87]
Hi, 
I am using EF6 in Code-First. I have the strange problem, that obviously defaults are not set in tables when the migration is applied using your Nuget-Package
ErikEJ.EntityFramework.SqlServer.

I use it by setting 
 DbConfiguration.SetConfiguration(new MicrosoftSqlDbConfiguration());
in the configure-Method in Startup. Authorization etc works fine (i am using Azure integrated authentication)

When checking the create-Statements of the created tables for example the following is missing:

```
ALTER TABLE [dbo].[MLRegistration] ADD  DEFAULT (getdate()) FOR [RegistrationTime]
GO
```

When creating the same table using another project which is not using your nuget-package (or removing it in the very same project), this line is there (and the defaults are applied).

The Migration-Code which should be applied looks like that:

`            CreateTable(
                "dbo.MLRegistration",
                c => new
                    {
                        UserName = c.String(nullable: false, maxLength: 128),
                        Disabled = c.Boolean(nullable: false),
                        RegistrationTime = c.DateTime(nullable: false,
                            annotations: new Dictionary<string, AnnotationValues>
                            {
                                { 
                                    "SqlDefaultValue",
                                    new AnnotationValues(oldValue: null, newValue: "getdate()")
                                },
                            }),
                    })
                .PrimaryKey(t => t.UserName);`

Maybe you can help me?

**Comment by ErikEJ** [comment]
Limited rights to the database?

I probably need a repro project.

**Comment by LeopoldLerch** [comment]
No, it is the same database, tried even with the same connectionstring (with user/password authentication)

When simply commenting out 
`DbConfiguration.SetConfiguration(new MicrosoftSqlDbConfiguration())`

the table is set up with correct defaults. When deleting the migration from history and the tables, remove the comment from the config above and rerunning it, the table is created also, but the defaults are not set.

Not limited to one table, i have 2 tables with the same issue.

**Comment by ErikEJ** [comment]
I need a simple repro.

**Comment by LeopoldLerch** [comment]
Will a Model help, from which you then can generate a migration for your database?

**Comment by ErikEJ** [comment]
Sure, an console app with just the model.

**Comment by LeopoldLerch** [comment]
[EFTestApp.zip](https://github.com/ErikEJ/EntityFramework6PowerTools/files/7267774/EFTestApp.zip)

You will need to insert your own connectionString of course. When commenting in the DBConfiguration-Line, the Defaults for the DateTime-Columns are not set. When commented out, they are correct.

Thanks

**Comment by ErikEJ** [comment]
Sure, create a seperate .csproj/package and use conditional compilation.

**Comment by CZEMacLeod** [comment]
@LeopoldLerch Pretty sure, as it is just a string value, you can register both and it will pickup based on the provider in use.

```cs
SetSqlGenerator("System.Data.SqlClient", new DefaultValueSqlServerMigrationSqlGenerator());
SetSqlGenerator("Microsoft.Data.SqlClient", new DefaultValueSqlServerMigrationSqlGenerator());
```

I have something very similar to the `DefaultValueSqlServerMigrationSqlGenerator` in my own code, although I have extension methods in the same library that sets up my DbMigrationsConfiguration and DBContexts which I call in the constructors.
This means that I should be able to just add the line to my extension method and all my libraries will be enabled for both providers.

**Comment by LeopoldLerch** [comment]
Sure that i can Register both? Dont they Override each other?

Will try in monday. Thx


Cynthia MacLeod ***@***.***> schrieb am Fr., 1. Okt. 2021,
17:47:
