### ISSUE TITLE
i have a problen with Visual Studio 2022 no can install ADO:NET EF6 Tolls

### ISSUE THREAD

**Issue by henrypandales** [ErikEJ/EntityFramework6PowerTools#90]
i have a problen with Visual Studio 2022 no can install ADO:NET EF6 Tolls 
What can do?

Please write me to my whatsapp +57 3147754208  from Colombia

**Comment by ErikEJ** [comment]
This is the wrong repository for this, I you need help with Visual Studio, use https://developercommunity.visualstudio.com/home
