### ISSUE TITLE
EntityFramework edmx does not support Provider="Microsoft.Data.SqlClient"

### ISSUE THREAD

**Issue by burrowj** [ErikEJ/EntityFramework6PowerTools#95]
Firstly thanks the workaround you have provided!

This is an issue that I think you are aware of but was wondering if you plan on adding a fix or if I'm doing something wrong.  I Have two projects.  The business project has the edmx file and designer.  The API project has the controllers.  With your software I can get everything to work as long as I change the edmx file set as below.

<edmx:StorageModels>
    <Schema Namespace="mycontainer.Store" Provider="Microsft.Data.SqlClient"

The projects build and it works but I get the following error in me business project

The ADO.NET provider with invariant name 'Microsoft.Data.SqlClient' is either not registered in the machine or application config file, or could not be loaded. 

and I can't load the visual edmx designer in except as XML.

If I want to work in the designer I have to change Provider="Microsft.Data.SqlClient" to Provider="System.Data.SqlClient" then change it back when finished.  If I leave it set to Provider="System.Data.SqlClient" it all compiles but when I use it get an error

"Unable to cast object of type Microsoft.Data.SqlClient.SqlConnection to type System.Data.SqlClient.SqlConnection"

Any tips?
Thanks
John

**Comment by ErikEJ** [comment]
This is a limitation in the Visual Studio designer, and out of my control. 
In other words, this package is a run-time solution, not a design time solution.
I will try to add this to the EDMX related docs.

**Comment by ErikEJ** [comment]
@burrowj Would be grateful if yo could have a look at the docs update here: https://github.com/ErikEJ/EntityFramework6PowerTools/commit/915dc4be3751351bc45b06f8e133e8241d0166a7
